/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:62
-- creates:
--   Type(pg_automerge::io::AutomergeDatum)
--   Type(pg_automerge::io::AutomergeArg)
--   Type(pg_automerge::io::AutomergeValue)


CREATE TYPE automerge;

CREATE FUNCTION automerge_in(cstring) RETURNS automerge
    IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'automerge_in_wrapper';
CREATE FUNCTION automerge_out(automerge) RETURNS cstring
    IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'automerge_out_wrapper';
CREATE FUNCTION automerge_recv(internal) RETURNS automerge
    IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'automerge_recv_wrapper';
CREATE FUNCTION automerge_send(automerge) RETURNS bytea
    IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'automerge_send_wrapper';

CREATE TYPE automerge (
    INPUT = automerge_in,
    OUTPUT = automerge_out,
    RECEIVE = automerge_recv,
    SEND = automerge_send,
    INTERNALLENGTH = VARIABLE,
    ALIGNMENT = int4,
    STORAGE = extended
);

COMMENT ON TYPE automerge IS
    'An Automerge CRDT document (uncompressed save format). Implicitly castable to jsonb.';
COMMENT ON FUNCTION automerge_in(cstring) IS
    'Input function of type automerge: \x followed by the hex of an Automerge save.';
COMMENT ON FUNCTION automerge_out(automerge) IS
    'Output function of type automerge: \x followed by the hex of the stored bytes.';
COMMENT ON FUNCTION automerge_recv(internal) IS
    'Binary input function of type automerge: an Automerge save.';
COMMENT ON FUNCTION automerge_send(automerge) IS
    'Binary output function of type automerge: the stored bytes.';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:16
-- requires:
--   automerge_type


-- One change of a document (automerge_changes, automerge_get_change).
CREATE TYPE automerge_change AS (
    hash text,          -- change hash, 64 lowercase hex digits
    actor text,         -- actor id, lowercase hex
    seq bigint,         -- 1, 2, ... per actor
    start_op bigint,    -- counter of the change's first op
    op_count bigint,    -- number of ops (0 for an empty change)
    "time" timestamptz, -- commit time (Unix seconds); NULL when not set
    message text,       -- commit message; NULL when not set
    deps text[],        -- sorted hashes of the changes it depends on
    change bytea        -- the change chunk, loadable by any Automerge
);
COMMENT ON TYPE automerge_change IS 'One change of an automerge document.';

-- The same without the change bytes (automerge_changes_meta).
CREATE TYPE automerge_change_meta AS (
    hash text,
    actor text,
    seq bigint,
    start_op bigint,
    op_count bigint,
    "time" timestamptz,
    message text,
    deps text[]
);
COMMENT ON TYPE automerge_change_meta IS
    'Metadata of one change of an automerge document (no change bytes).';
/* </end connected objects> */

/* <begin connected objects> */
-- src/notify.rs:133
-- requires:
--   automerge_type


CREATE FUNCTION automerge_notify() RETURNS trigger
    LANGUAGE c AS 'MODULE_PATHNAME', 'automerge_notify_wrapper';
COMMENT ON FUNCTION automerge_notify() IS
    'AFTER INSERT OR UPDATE OR DELETE FOR EACH ROW trigger: automerge_notify(channel, key_column [, ...]) sends NOTIFY channel with the row key and the heads of changed automerge columns.';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:220
-- pg_automerge::history::automerge_change_count
CREATE  FUNCTION "automerge_change_count"(
	"doc" automerge /* AutomergeArg */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_change_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:149
-- pg_automerge::history::automerge_changes
-- requires:
--   automerge_change_types
CREATE  FUNCTION "automerge_changes"(
	"doc" automerge, /* AutomergeArg */
	"since_heads" TEXT[] DEFAULT '{}' /* Vec < Option < String > > */
) RETURNS SETOF automerge_change /* :: pgrx :: heap_tuple :: PgHeapTuple < '_, :: pgrx :: pgbox :: AllocatedByRust
> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_changes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:189
-- pg_automerge::history::automerge_changes_bytes
CREATE  FUNCTION "automerge_changes_bytes"(
	"doc" automerge, /* AutomergeArg */
	"since_heads" TEXT[] DEFAULT '{}' /* Vec < Option < String > > */
) RETURNS bytea /* Vec < u8 > */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_changes_bytes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:168
-- pg_automerge::history::automerge_changes_meta
-- requires:
--   automerge_change_types
CREATE  FUNCTION "automerge_changes_meta"(
	"doc" automerge, /* AutomergeArg */
	"since_heads" TEXT[] DEFAULT '{}' /* Vec < Option < String > > */
) RETURNS SETOF automerge_change_meta /* :: pgrx :: heap_tuple :: PgHeapTuple < '_, :: pgrx :: pgbox :: AllocatedByRust
> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_changes_meta_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/introspect.rs:24
-- pg_automerge::introspect::automerge_contains
CREATE  FUNCTION "automerge_contains"(
	"a" automerge, /* AutomergeArg */
	"b" automerge /* AutomergeArg */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/introspect.rs:63
-- pg_automerge::introspect::automerge_contains
CREATE  FUNCTION "automerge_contains"(
	"doc" automerge, /* AutomergeArg */
	"changes" bytea /* & [u8] */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_contains_changes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:113
-- pg_automerge::io::automerge_from_bytea
CREATE  FUNCTION "automerge_from_bytea"(
	"bytes" bytea /* & [u8] */
) RETURNS automerge /* AutomergeValue */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_from_bytea_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:204
-- pg_automerge::history::automerge_get_change
-- requires:
--   automerge_change_types
CREATE  FUNCTION "automerge_get_change"(
	"doc" automerge, /* AutomergeArg */
	"hash" TEXT /* & str */
) RETURNS automerge_change /* Option < :: pgrx :: heap_tuple :: PgHeapTuple < '_, :: pgrx :: pgbox ::
AllocatedByRust > > */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_get_change_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/introspect.rs:13
-- pg_automerge::introspect::automerge_heads
CREATE  FUNCTION "automerge_heads"(
	"doc" automerge /* AutomergeArg */
) RETURNS TEXT[] /* Vec < String > */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_heads_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/introspect.rs:81
-- requires:
--   automerge_heads
--   automerge_contains
--   automerge_contains_changes


COMMENT ON FUNCTION automerge_heads(automerge) IS
    'Current heads as sorted hex change hashes, read from the stored header without loading the document.';
COMMENT ON FUNCTION automerge_contains(automerge, automerge) IS
    'Whether a already has every change of b, i.e. merge(a, b) adds nothing.';
COMMENT ON FUNCTION automerge_contains(automerge, bytea) IS
    'Whether every change in an Automerge save or change chunks is already in the document, i.e. merge(doc, changes) adds nothing.';
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:19
-- pg_automerge::io::automerge_in
-- Skipped due to `#[pgrx(sql = false)]`
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:197
-- pg_automerge::merge::automerge_merge_agg_final
CREATE  FUNCTION "automerge_merge_agg_final"(
	"state" internal /* Internal */
) RETURNS automerge /* Option < AutomergeValue > */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_merge_agg_final_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:157
-- pg_automerge::merge::automerge_merge_agg_trans
CREATE  FUNCTION "automerge_merge_agg_trans"(
	"state" internal, /* Internal */
	"value" automerge /* Option < AutomergeArg > */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_merge_agg_trans_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:209
-- requires:
--   automerge_type
--   automerge_merge_agg_trans
--   automerge_merge_agg_final


CREATE AGGREGATE merge_agg(automerge) (
    SFUNC = automerge_merge_agg_trans,
    STYPE = internal,
    FINALFUNC = automerge_merge_agg_final,
    -- The state is a fully loaded document in the Rust heap, invisible to
    -- Postgres memory accounting and not spillable by HashAgg (no
    -- serialfunc). Declare a size that is realistic for non-trivial
    -- documents (the default estimate for internal is ~8kB) so the planner
    -- prefers sorted grouping over large per-group hash tables.
    SSPACE = 1048576,
    PARALLEL = SAFE
);

COMMENT ON AGGREGATE merge_agg(automerge) IS 'CRDT merge of all non-null inputs.';
COMMENT ON FUNCTION automerge_merge_agg_trans(internal, automerge) IS 'Transition function of merge_agg.';
COMMENT ON FUNCTION automerge_merge_agg_final(internal) IS 'Final function of merge_agg.';
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:77
-- pg_automerge::merge::automerge_merge_support
CREATE  FUNCTION "automerge_merge_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_merge_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:29
-- pg_automerge::io::automerge_out
-- Skipped due to `#[pgrx(sql = false)]`
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:35
-- pg_automerge::io::automerge_recv
-- Skipped due to `#[pgrx(sql = false)]`
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:54
-- pg_automerge::io::automerge_send
-- Skipped due to `#[pgrx(sql = false)]`
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:119
-- pg_automerge::io::automerge_to_jsonb
CREATE  FUNCTION "automerge_to_jsonb"(
	"doc" automerge /* AutomergeArg */
) RETURNS jsonb /* JsonbDatum */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_to_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/io.rs:133
-- requires:
--   automerge_type
--   automerge_from_bytea
--   automerge_to_jsonb


CREATE CAST (bytea AS automerge) WITH FUNCTION automerge_from_bytea(bytea) AS ASSIGNMENT;
-- Same varlena layout: the stored bytes are a valid Automerge save.
CREATE CAST (automerge AS bytea) WITHOUT FUNCTION;
-- The only implicit cast from automerge, so every jsonb operator and
-- function applies to automerge values directly.
CREATE CAST (automerge AS jsonb) WITH FUNCTION automerge_to_jsonb(automerge) AS IMPLICIT;

COMMENT ON FUNCTION automerge_from_bytea(bytea) IS
    'An Automerge save (or change chunks) as an automerge value, validated and normalized; the bytea to automerge cast.';
COMMENT ON FUNCTION automerge_to_jsonb(automerge) IS
    'The current state of the document as jsonb; the implicit automerge to jsonb cast.';
COMMENT ON CAST (bytea AS automerge) IS
    'Assignment cast: validates and normalizes an Automerge save.';
COMMENT ON CAST (automerge AS bytea) IS
    'Explicit cast: the stored Automerge bytes (an uncompressed save).';
COMMENT ON CAST (automerge AS jsonb) IS
    'Implicit cast: the current state of the document as jsonb.';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:231
-- pg_automerge::history::automerge_to_jsonb
CREATE  FUNCTION "automerge_to_jsonb"(
	"doc" automerge, /* AutomergeArg */
	"heads" TEXT[] /* Vec < Option < String > > */
) RETURNS jsonb /* JsonbDatum */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'automerge_to_jsonb_at_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/history.rs:244
-- requires:
--   automerge_changes
--   automerge_changes_meta
--   automerge_changes_bytes
--   automerge_get_change
--   automerge_change_count
--   automerge_to_jsonb_at


COMMENT ON FUNCTION automerge_changes(automerge, text[]) IS
    'Every change not reachable from since_heads (all by default), dependencies first, with its bytes.';
COMMENT ON FUNCTION automerge_changes_meta(automerge, text[]) IS
    'Every change not reachable from since_heads (all by default), dependencies first, without its bytes.';
COMMENT ON FUNCTION automerge_changes_bytes(automerge, text[]) IS
    'The changes not reachable from since_heads as concatenated change chunks (save_after).';
COMMENT ON FUNCTION automerge_get_change(automerge, text) IS
    'The change with the given hash, with its bytes; NULL if the document does not have it.';
COMMENT ON FUNCTION automerge_change_count(automerge) IS 'Number of changes in the document.';
COMMENT ON FUNCTION automerge_to_jsonb(automerge, text[]) IS
    'The state of the document as of the given heads as jsonb (''{}'': before any change).';
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:18
-- pg_automerge::merge::merge
-- requires:
--   automerge_merge_support
CREATE  FUNCTION "merge"(
	"a" automerge, /* AutomergeArg */
	"b" automerge /* AutomergeArg */
) RETURNS automerge /* AutomergeValue */
IMMUTABLE STRICT PARALLEL SAFE SUPPORT "automerge_merge_support"
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'merge_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:50
-- pg_automerge::merge::merge
-- requires:
--   automerge_merge_support
CREATE  FUNCTION "merge"(
	"doc" automerge, /* AutomergeArg */
	"changes" bytea /* & [u8] */
) RETURNS automerge /* AutomergeValue */
IMMUTABLE STRICT PARALLEL SAFE SUPPORT "automerge_merge_support" 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'merge_bytea_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/merge.rs:121
-- requires:
--   automerge_type
--   merge
--   merge_bytea
--   automerge_merge_support


CREATE OPERATOR || (
    LEFTARG = automerge,
    RIGHTARG = automerge,
    FUNCTION = merge,
    COMMUTATOR = ||
);
-- No commutator: there is no bytea || automerge.
CREATE OPERATOR || (
    LEFTARG = automerge,
    RIGHTARG = bytea,
    FUNCTION = merge
);

COMMENT ON FUNCTION merge(automerge, automerge) IS
    'CRDT merge: a plus every change of b it lacks. Commutative and idempotent in state.';
COMMENT ON FUNCTION merge(automerge, bytea) IS
    'Apply an Automerge save or change chunks (save_incremental / save_after output) on top of the document.';
COMMENT ON FUNCTION automerge_merge_support(internal) IS
    'Planner support function of merge: lets PL/pgSQL merge into a variable in place.';
COMMENT ON OPERATOR || (automerge, automerge) IS 'merge(automerge, automerge): CRDT merge.';
COMMENT ON OPERATOR || (automerge, bytea) IS
    'merge(automerge, bytea): apply an Automerge save or change chunks.';
/* </end connected objects> */

